# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5c9c18ba824b73d4b4e6300e03bffcf9"
name = "frequently-bought-together"
application_url = "https://standing-whenever-fed-hardwood.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appdevelopment-ac.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://standing-whenever-fed-hardwood.trycloudflare.com/auth/callback",
  "https://standing-whenever-fed-hardwood.trycloudflare.com/auth/shopify/callback",
  "https://standing-whenever-fed-hardwood.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
